hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

run:
  predict: false
  checkpoint_path: null

data:
  num_classes: 1
  dataset_path: examples/poverty/dataset/
  labels_name: observation_2013+.csv
  train_batch_size: 64
  inference_batch_size: 64
  num_workers: 8

task:
  task: regression

trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 100
  check_val_every_n_epoch: 1

model:
  provider_name: torchvision
  model_name: resnet18
  model_kwargs:
    weights: ResNet18_Weights.DEFAULT
    num_classes: null
    in_chans: null
    output_stride: null
    global_pool: null
  modifiers:
    change_first_convolutional_layer:
      num_input_channels: 7
    change_last_layer:
      num_outputs: 1

optimizer:
  lr: 1.0e-04
  weight_decay: 1.0e-05
  momentum: 0.9
  nesterov: true
  metrics:
    regression_R2score:
      callable: Fmetrics.regression.r2_score
      kwargs: null


miscellaneous:
  train_dataset : random 0.5
  val_dataset : train_dataset
  optimizer : Adam
  lr_scheduler : ReduceLROnPlateau
        
