hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

trainer:
  # gpus: 1  # Deprecated since pytorchlightning 1.7, removed in 2.0. Replaced by the 2 next attributes
  accelerator: "gpu"
  devices: 'auto'
  max_epochs: 30
  val_check_interval: 500
  check_val_every_n_epoch: 1
  log_every_n_steps: 500

run:
  predict: false
  checkpoint_path: # "outputs/cnn_on_rgbnir_torchgeo/2024-04-04_23-24-49/last.ckpt"

model:
  provider_name: "timm" # choose from ["timm", "torchvision"]
  model_name: "resnet18"
  model_kwargs:
    pretrained: true # Deprecated in torchvision since 0.13 (replaced by "weights") but used by timm
    num_classes:
    in_chans:
    output_stride:
    global_pool:
  modifiers:
    change_first_convolutional_layer:
      num_input_channels: 1
    change_last_layer:
      num_outputs: 1734

optimizer:
  lr: 1e-2
  weight_decay: 0
  momentum: 0.9
  nesterov: true
  metrics:
    # binary_accuracy:
    #   # callable: 'Fmetrics.accuracy'
    #   kwargs: {}
    multilabel_accuracy:
      # callable: 'Fmetrics.classification.multilabel_accuracy'
      kwargs:
        num_labels: 1734
    multilabel_recall:
      callable: 'Fmetrics.classification.multilabel_recall'
      kwargs:
        num_labels: 1734
    multilabel_precision:
      callable: 'Fmetrics.classification.multilabel_precision'
      kwargs:
        num_labels: 1734
    multilabel_f1-score:
      callable: 'Fmetrics.classification.multilabel_f1_score'
      kwargs:
        num_labels: 1734
    # multilabel_accuracy:
    #   # callable: 'Fmetrics.classification.multilabel_accuracy'
    #   kwargs:
    #     num_labels: 5

data:
  dataset_path: "dataset/"
  labels_name: "dataset_belgium.csv"
  download_data_sample: False
  train_batch_size: 32
  inference_batch_size: 16
  num_workers: 8
  units: "pixel"
  crs: 3035

task:
  task: "classification_multilabel" # ['classification_binary', 'classification_multiclass', 'classification_multilabel']
