name: Publish documentation

on:
    push:

jobs:
    test:
        name: Unit Test 
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.8"]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              name: Setup python ${{ matrix.python-version }}
              with:
                python-version: ${{ matrix.python-version }}
                cache: 'pip' # caching pip dependencies
            - name: pip install -r requirements.txt
              run: pip install -r ./requirements.txt
            - name: pip install -e .
              run: |
                pip install -e .
                pip install sphinx-rtd-theme==1.2.0
            - name: Install Sphynx doc
              run: sudo apt-get install python3-sphinx
            - name: Make documentation
              run: make -C docs html
